"""update role type

Revision ID: 46b9c4e10e02
Revises: 591c28449bc1
Create Date: 2023-01-23 18:37:48.992068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46b9c4e10e02"
down_revision = "591c28449bc1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
